#!/usr/bin/env python3
"""Train the distillation policy; use --help for data and launch options."""

from scripts._training import launch

CLI = [
    'exp:g1-29dof-wbt-w-object-pure-rl-policy-command-after-lift',
    'termination:g1-29dof-wbt-generalist-z-only',
    'randomization:g1_29dof_wbt_w_object_pure_rl',
    'command:g1-29dof-wbt-w-object-generalist',
    'reward:g1-29dof-wbt-w-object-generalist-tracking-no-contact',
    'perception:camera_depth_d435i',
    'logger:wandb',
    'observation:g1-29dof-wbt-w-object-distill-sparse-root-cmd-teacher-linvel',
    '--training.project=${WANDB_PROJECT}',
    '--training.seed=42',
    '--training.multigpu=True',
    '--training.export-onnx=True',
    '--algo.config.num-steps-per-env=24',
    '--algo.config.num-learning-epochs=7',
    '--algo.config.num-mini-batches=4',
    '--algo.config.clip-param=0.2',
    '--algo.config.gamma=0.99',
    '--algo.config.lam=0.95',
    '--algo.config.value-loss-coef=1.0',
    '--algo.config.entropy-coef=0.005',
    '--algo.config.max-grad-norm=1.0',
    '--algo.config.schedule=adaptive',
    '--algo.config.desired-kl=0.01',
    '--algo.config.actor-learning-rate=0.001',
    '--algo.config.critic-learning-rate=0.001',
    '--algo.config.min-actor-learning-rate=0.00001',
    '--algo.config.max-actor-learning-rate=0.01',
    '--algo.config.min-critic-learning-rate=0.00001',
    '--algo.config.max-critic-learning-rate=0.01',
    '--algo.config.init-noise-std=1.0',
    '--algo.config.module-dict.actor.min-noise-std=0.01',
    '--algo.config.normalize-actor-obs=False',
    '--algo.config.normalize-critic-obs=False',
    '--algo.config.reset-rollout-at-checkpoint=False',
    '--algo.config.module-dict.critic.layer-config.hidden-dims=[512,256,128]',
    "--algo.config.module-dict.actor.input-dim=['actor_obs_root_contact_aware','actor_obs_drop_button','actor_obs_proprio_with_actions_no_linvel']",
    '--algo.config.module-dict.actor.layer-config.hidden-dims=[512,256,128]',
    '--algo.config.module-dict.actor.type=MLP',
    '--algo.config.module-dict.critic.type=MLP',
    '--observation.groups.actor_obs_root_contact_aware.history-length=1',
    '--observation.groups.actor_obs_drop_button.history-length=1',
    '--observation.groups.actor_obs_proprio_with_actions_no_linvel.history-length=1',
    '--observation.groups.critic_proprio_history.history-length=1',
    '--command.setup-terms.motion-command.params.motion-config.pure-rl-policy-command-after-lift-enabled=False',
    '--command.setup-terms.motion-command.params.motion-config.hybrid-stage2-enabled=False',
    '--command.setup-terms.motion-command.params.motion-config.hybrid-velocity-enabled=False',
    '--command.setup-terms.motion-command.params.motion-config.zero-root-command-when-drop-active=True',
    '--command.setup-terms.motion-command.params.motion-config.clip-weighting-strategy=uniform_clip',
    '--command.setup-terms.motion-command.params.motion-config.pair-terrain-with-motion=False',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob=0.0',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob-start-iter=0',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob=0.0',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob-end=0.0',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob-start-iter=0',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.overall-noise-scale=1.0',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.dof-pos=0.1',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.dof-vel=0.0',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-pos=[0.08,0.08,0.025]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-rot=[0.15,0.15,0.30]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-lin-vel=[0.20,0.20,0.10]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-ang-vel=[0.25,0.25,0.35]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.object-pos=[0.08,0.08,0.0]',
    '--command.setup-terms.motion-command.params.motion-config.enable-default-pose-prepend=True',
    '--command.setup-terms.motion-command.params.motion-config.default-pose-prepend-duration-s=0.2',
    '--command.setup-terms.motion-command.params.motion-config.enable-default-pose-append=True',
    '--command.setup-terms.motion-command.params.motion-config.default-pose-append-duration-s=2.0',
    '--perception.camera-apply-sensor-noise=False',
    '--perception.sensor-offset=[0.01,0.01,0.44]',
    '--perception.camera-pitch-deg=10.0',
    '--perception.camera-warp-edge-noise=True',
    '--perception.camera-warp-enable-holes=True',
    '--perception.camera-warp-hole-prob=0.2',
    '--perception.camera-warp-additive-noise-std=0.03',
    '--perception.camera-warp-depth-offset-std=0.03',
    '--perception.object-geometry-mode=mesh',
    '--perception.camera-mount-quat=[0.00644801,0.23350163,0.00644801,0.97231365]',
    '--perception.camera-frame-quat=[-0.5,0.5,-0.5,0.5]',
    '--robot.object.enabled=True',
    '--simulator.config.scene.env-spacing=5.0',
    '--simulator.config.sim.max-episode-length-s=10.0',
    '--simulator.config.sim.physx.gpu-found-lost-pairs-capacity=335544320',
    '--simulator.config.sim.physx.gpu-found-lost-aggregate-pairs-capacity=469762048',
    '--simulator.config.sim.physx.gpu-total-aggregate-pairs-capacity=83886080',
    '--simulator.config.sim.physx.gpu-collision-stack-size=268435456',
    '--logger.entity=${WANDB_ENTITY}',
    '--logger.video.enabled=False',
    '--logger.headless-recording=False',
    '--logger.video.upload-to-wandb=False',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-sparse-root-command-mode=precomputed_turn_then_forward',
    '--termination.terms.bad_tracking.params.bad-ref-pos-threshold=1.5',
    '--termination.terms.bad_tracking.params.bad-ref-ori-threshold=1.65',
    '--termination.terms.bad_tracking.params.bad-motion-body-pos-threshold=0.75',
    '--termination.terms.bad_tracking.params.bad-object-pos-threshold=0.75',
    '--termination.terms.bad_tracking.params.bad-object-ori-threshold=1.65',
    '--training.policy-init-checkpoint=${INITIALIZER_CHECKPOINT}',
    '--perception.camera-body-name=torso_link',
    '--perception.camera-width=106',
    '--perception.camera-height=60',
    '--perception.update-hz=30.0',
    '--perception.camera-fps=30.0',
    '--perception.camera-near=0.3',
    '--perception.camera-far=3.0',
    '--perception.max-distance=3.0',
    '--perception.camera-warp-preprocess=True',
    '--perception.camera-warp-resize=(58,87)',
    '--perception.camera-warp-crop-top=2',
    '--perception.camera-warp-crop-bottom=0',
    '--perception.camera-warp-crop-left=4',
    '--perception.camera-warp-crop-right=4',
    '--perception.camera-warp-normalize=True',
    '--perception.camera-warp-latency-frame=(3,4)',
    '--perception.camera-warp-buffer-len=6',
    '--perception.encoder-pretrained=False',
    '--perception.encoder-freeze-backbone=False',
    '--perception.camera-warp-hole-reference-batch-size=4096',
    '--perception.camera-warp-hole-seed-semantics=legacy_fixed_v1',
    '--perception.reset-refresh-semantics=legacy_full_v1',
    "--perception.camera-mesh-file-map={'pelvis': 'pelvis.STL', 'left_hip_pitch_link': 'left_hip_pitch_link.STL', 'left_hip_roll_link': 'left_hip_roll_link.STL', 'left_hip_yaw_link': 'left_hip_yaw_link.STL', 'left_knee_link': 'left_knee_link.STL', 'left_ankle_pitch_link': 'left_ankle_pitch_link.STL', 'left_ankle_roll_link': 'left_ankle_roll_link.STL', 'right_hip_pitch_link': 'right_hip_pitch_link.STL', 'right_hip_roll_link': 'right_hip_roll_link.STL', 'right_hip_yaw_link': 'right_hip_yaw_link.STL', 'right_knee_link': 'right_knee_link.STL', 'right_ankle_pitch_link': 'right_ankle_pitch_link.STL', 'right_ankle_roll_link': 'right_ankle_roll_link.STL', 'waist_yaw_link': 'waist_yaw_link_rev_1_0.STL', 'waist_roll_link': 'waist_roll_link_rev_1_0.STL', 'left_shoulder_pitch_link': 'left_shoulder_pitch_link.STL', 'left_shoulder_roll_link': 'left_shoulder_roll_link.STL', 'left_shoulder_yaw_link': 'left_shoulder_yaw_link.STL', 'left_elbow_link': 'left_elbow_link.STL', 'left_wrist_roll_link': 'left_wrist_roll_link.STL', 'left_wrist_pitch_link': 'left_wrist_pitch_link.STL', 'left_wrist_yaw_link': 'combined_left_wrist_rubberhand.STL', 'right_shoulder_pitch_link': 'right_shoulder_pitch_link.STL', 'right_shoulder_roll_link': 'right_shoulder_roll_link.STL', 'right_shoulder_yaw_link': 'right_shoulder_yaw_link.STL', 'right_elbow_link': 'right_elbow_link.STL', 'right_wrist_roll_link': 'right_wrist_roll_link.STL', 'right_wrist_pitch_link': 'right_wrist_pitch_link.STL', 'right_wrist_yaw_link': 'combined_right_wrist_rubberhand.STL'}",
    '--robot.asset.asset-root=${ROBOT_ASSETS}',
    '--training.name=${RUN_NAME}',
    '--training.num-envs=16384',
    '--training.policy-init-actor-contract-migration=box_tracking_to_precomputed_peak_height_sw_depth_mesh_v1',
    '--algo.config.distill.enabled=True',
    '--algo.config.num-learning-iterations=40000',
    '--algo.config.save-interval=500',
    '--reward.terms.offline-contact-guidance.weight=1.0',
    '--reward.terms.offline-contact-guidance.params.contact-weight=1.0',
    '--reward.terms.offline-contact-guidance.params.wrist-weight=1.0',
    '--reward.terms.offline-contact-guidance.params.contact-export-root=${CONTACT_BANK}',
    '--reward.terms.offline-contact-guidance.params.contact-schedule-missing-mode=inactive',
    '--reward.terms.offline-contact-guidance.params.contact-region-names=["left_wrist", "right_wrist", "left_elbow", "right_elbow", "left_wrist_roll", "right_wrist_roll", "left_wrist_pitch", "right_wrist_pitch", "torso"]',
    '--reward.terms.offline-contact-guidance.params.wrist-region-names=["left_wrist","right_wrist"]',
    '--robot.object.object-urdf-path=${MOTION_BANK}/_clip_object_urdf_map.json',
    '--logger.name=${RUN_NAME}',
    '--logger.mode=online',
    '--logger.base-dir=${LOG_DIR}',
    '--command.setup-terms.motion-command.params.motion-config.motion-file=${MOTION_BANK}',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-button-window-mode=peak_height',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-carry-window-mode=peak_height',
    '--command.setup-terms.motion-command.params.motion-config.use-adaptive-timesteps-sampler=False',
    '--command.setup-terms.motion-command.params.motion-config.adaptive-sampling-contact-interval-root=${CONTACT_BANK}',
    '--command.setup-terms.motion-command.params.motion-config.contact-interval-runtime-prepend-compensation=True',
    '--command.setup-terms.motion-command.params.motion-config.uniform-t1-window-sampling-enabled=False',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob-end=1.0',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob-end-iter=39999',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob-end-iter=39999',
    '--algo.config.distill.mode=dagger',
    '--algo.config.distill.policy-to-clone=${TEACHER_CHECKPOINT}',
    '--algo.config.distill.teacher-obs-keys=["actor_obs"]',
    '--algo.config.distill.strict-teacher-load=True',
    '--algo.config.distill.teacher-action-mix-ratio=0.0',
    '--algo.config.distill.take-teacher-actions=False',
    '--algo.config.distill.teacher-use-stochastic-actions=False',
    '--algo.config.distill.dagger-match-std=True',
    '--algo.config.distill.dagger-loss-coef=1.0',
    '--algo.config.distill.dagger-replay-enabled=False',
    '--algo.config.distill.ppo-start-epoch=0',
    '--algo.config.distill.ppo-start-coeff=0.01',
    '--algo.config.distill.ppo-target-coeff=0.9',
    '--algo.config.distill.ppo-schedule-step-epochs=700',
    '--algo.config.distill.dagger-end-epoch=6300',
    '--algo.config.distill.ppo-start-noise-std=None',
    '--algo.config.distill.fixed-bc-eval-log-interval=100',
    '--algo.config.distill.fixed-bc-guard-enabled=False',
    '--logger.resume=never',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-peak-height-alpha=0.91',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-peak-height-smoothing-steps=5',
]

ENVIRONMENT = {
    'CONTACT_EXPORT_ROOT': '${CONTACT_BANK}',
    'CONTACT_SIDECAR_MODE': 'runtime-intervals',
    'CUBLAS_WORKSPACE_CONFIG': ':4096:8',
    'CUDA_DEVICE_ORDER': 'PCI_BUS_ID',
    'HOLOSOMA_ACTIVATE_OBJECT_CONTACT_SENSORS': '0',
    'HOLOSOMA_ALLOW_LEGACY_OBJECT_URDF_FALLBACK': '0',
    'HOLOSOMA_CONTIGUOUS_MINIBATCHES': '1',
    'HOLOSOMA_DISABLE_AUTO_RESET': '0',
    'HOLOSOMA_DISABLE_CLIP_END_RESET': '0',
    'HOLOSOMA_DISABLE_MOTION_END_RESET': '0',
    'HOLOSOMA_EXTERNAL_AS_MOTION_GENERATOR_TEACHER_SHA256': '14e644323b8e6a7b769dbf641d9f625bee895742b7064368b55afd0710a0d665',
    'HOLOSOMA_EXTERNAL_AS_RANK_SHARD_SOURCE_DIGEST': '315628d1d27ec6c517cf13c6826f4efa6dc76efc312516dc4d849a35cc4512c2',
    'HOLOSOMA_EXTERNAL_AS_SINGLE_SLOT_DIR': '${MOTION_BANK}',
    'HOLOSOMA_EXTERNAL_AS_SINGLE_SLOT_SOURCE_DIGEST': '39826c72c99c0d5544b5a434484c9beee302e9e681736cfc8daabb1ffbdf1d26',
    'HOLOSOMA_EXTERNAL_AS_SINGLE_SLOT_VIEW_DIGEST': '7a7433fe27a16f8bdb59276e62895692b4297e793466d1b2f871dd6c238d37dc',
    'HOLOSOMA_EXTERNAL_AS_WORLD_SIZE': '8',
    'HOLOSOMA_GLOO_BARRIER': '1',
    'HOLOSOMA_GLOO_GRAD_REDUCE': '1',
    'HOLOSOMA_GLOO_SMALL_COLLECTIVES': '1',
    'HOLOSOMA_HIERARCHICAL_GRAD_REDUCE': '0',
    'HOLOSOMA_HIERARCHICAL_GRAD_REDUCE_CPU_LEADER': '0',
    'HOLOSOMA_HIERARCHICAL_PG_TIMEOUT_SEC': '300',
    'HOLOSOMA_HIERARCHICAL_SMALL_COLLECTIVES': '0',
    'HOLOSOMA_MINIBATCH_THROUGHPUT_CANARY': '0',
    'HOLOSOMA_MOTION_METRICS_INTERVAL': '16',
    'HOLOSOMA_MOTION_SHARD_MANIFEST': '${MOTION_BANK}/_rank_shards/by-source/315628d1d27ec6c517cf13c6826f4efa6dc76efc312516dc4d849a35cc4512c2/ws8/manifest.json',
    'HOLOSOMA_OBJECT_COLLIDER_TYPE': 'convex_decomposition',
    'HOLOSOMA_OBJECT_SPAWN_MODE': 'single_slot_multi_urdf',
    'HOLOSOMA_PERCEPTION_INCLUDE_ROBOT_MESH': '1',
    'HOLOSOMA_PERCEPTION_INJECT_INTO_POLICY_MODULES': 'True',
    'HOLOSOMA_PERCEPTION_OBJECT_GEOMETRY_MODE': 'mesh',
    'HOLOSOMA_RANK_LOCAL_CPU_AFFINITY': '1',
    'HOLOSOMA_RANK_LOCAL_MOTION_ROOT': '${MOTION_BANK}/_rank_shards/by-source/315628d1d27ec6c517cf13c6826f4efa6dc76efc312516dc4d849a35cc4512c2/ws8',
    'HOLOSOMA_RANK_LOCAL_SHARDING_ENABLED': '1',
    'HOLOSOMA_RANK_VISIBLE_DEVICES': '1',
    'HOLOSOMA_REQUIRE_CONTACT_INTERVAL_COVERAGE': '0',
    'HOLOSOMA_REQUIRE_CONTACT_TARGET_COVERAGE': '0',
    'HOLOSOMA_REQUIRE_OBJECT_MESH_ASSETS': '1',
    'HOLOSOMA_REQUIRE_RANK_LOCAL_SHARD_PROVENANCE': '1',
    'HOLOSOMA_REQUIRE_SINGLE_SLOT_OBJECTS': '1',
    'HOLOSOMA_REQUIRE_WANDB_RUN': '1',
    'HOLOSOMA_SHARD_OBJECT_ASSETS_BY_RANK': '0',
    'HOLOSOMA_SKIP_INITIAL_CHECKPOINT': '1',
    'HOLOSOMA_SYNC_AFTER_GRAD_ALLREDUCE': '0',
    'HOLOSOMA_SYNC_AFTER_OPTIMIZER_STEP': '0',
    'HOLOSOMA_SYNC_BEFORE_GRAD_ALLREDUCE': '1',
    'NNODES': '1',
    'NPROC': '8',
    'OMP_NUM_THREADS': '1',
    'PYTHONDONTWRITEBYTECODE': '1',
    'PYTHONHASHSEED': '0',
    'PYTHONNOUSERSITE': '1',
    'PYTORCH_CUDA_ALLOC_CONF': 'expandable_segments:True',
    'REQUIRE_MOTION_GENERATOR_TEACHER_MATCH': '0',
    'TORCH_ALLOW_TF32_CUBLAS_OVERRIDE': '1',
    'TORCH_DIST_BACKEND': 'gloo',
    'TORCH_DIST_TIMEOUT_SEC': '1800',
    'WANDB_CONSOLE': 'off',
    'WANDB_ENTITY': '${WANDB_ENTITY}',
    'WANDB_MODE': 'online',
    'WANDB_PROJECT': '${WANDB_PROJECT}',
    'WANDB_RESUME': 'never',
}

if __name__ == "__main__":
    launch("distillation", CLI, ENVIRONMENT, nodes=1)
