#!/usr/bin/env python3
"""Train the teacher policy; use --help for data and launch options."""

from scripts._training import launch

CLI = [
    'exp:g1-29dof-wbt-w-object-generalist-teacher-linvel',
    'command:g1-29dof-wbt-w-object-generalist',
    'reward:g1-29dof-wbt-w-object-generalist-tracking-no-contact',
    'perception:camera_depth_d435i',
    'termination:g1-29dof-wbt-generalist',
    'randomization:g1-29dof-wbt-w-object-teacher-state-robust-with-camera',
    'logger:wandb',
    '--training.project=${WANDB_PROJECT}',
    '--training.name=${RUN_NAME}',
    '--training.num-envs=${TOTAL_ENVS}',
    '--training.seed=42',
    '--training.multigpu=${MULTIGPU}',
    '--training.export-onnx=True',
    '--algo.config.distill.enabled=False',
    '--algo.config.num-learning-iterations=${ITERATIONS}',
    '--algo.config.num-steps-per-env=24',
    '--algo.config.num-learning-epochs=7',
    '--algo.config.num-mini-batches=4',
    '--algo.config.clip-param=0.2',
    '--algo.config.gamma=0.99',
    '--algo.config.lam=0.95',
    '--algo.config.value-loss-coef=1.0',
    '--algo.config.entropy-coef=0.005',
    '--algo.config.max-grad-norm=1.0',
    '--algo.config.schedule=adaptive',
    '--algo.config.desired-kl=0.01',
    '--algo.config.actor-learning-rate=0.001',
    '--algo.config.critic-learning-rate=0.001',
    '--algo.config.min-actor-learning-rate=0.00001',
    '--algo.config.max-actor-learning-rate=0.01',
    '--algo.config.min-critic-learning-rate=0.00001',
    '--algo.config.max-critic-learning-rate=0.01',
    '--algo.config.init-noise-std=1.0',
    '--algo.config.module-dict.actor.min-noise-std=0.01',
    '--algo.config.normalize-actor-obs=False',
    '--algo.config.normalize-critic-obs=False',
    '--algo.config.init-at-random-ep-len=True',
    '--algo.config.save-interval=1000',
    '--algo.config.reset-rollout-at-checkpoint=False',
    "--algo.config.module-dict.actor.input-dim=['actor_obs']",
    '--algo.config.module-dict.actor.layer-config.hidden-dims=[512,256,128]',
    "--algo.config.module-dict.critic.input-dim=['critic_obs']",
    '--algo.config.module-dict.critic.layer-config.hidden-dims=[512,256,128]',
    '--algo.config.module-dict.actor.type=MLP',
    '--algo.config.module-dict.critic.type=MLP',
    '--observation.groups.actor_obs.history-length=1',
    '--observation.groups.critic_obs.history-length=1',
    '--command.setup-terms.motion-command.params.motion-config.motion-file=${TEACHER_MOTION_BANK}',
    '--command.setup-terms.motion-command.params.motion-config.pure-rl-policy-command-after-lift-enabled=False',
    '--command.setup-terms.motion-command.params.motion-config.hybrid-stage2-enabled=False',
    '--command.setup-terms.motion-command.params.motion-config.hybrid-velocity-enabled=False',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-sparse-root-command-mode=tracking_error',
    '--command.setup-terms.motion-command.params.motion-config.zero-root-command-when-drop-active=True',
    '--command.setup-terms.motion-command.params.motion-config.clip-weighting-strategy=uniform_clip',
    '--command.setup-terms.motion-command.params.motion-config.pair-terrain-with-motion=False',
    '--command.setup-terms.motion-command.params.motion-config.use-adaptive-timesteps-sampler=False',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob=0.2',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob-end=0.2',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob-start-iter=0',
    '--command.setup-terms.motion-command.params.motion-config.start-at-timestep-zero-prob-end-iter=${LAST_ITERATION}',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob=0.0',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob-end=0.0',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob-start-iter=0',
    '--command.setup-terms.motion-command.params.motion-config.freeze-at-timestep-zero-prob-end-iter=${LAST_ITERATION}',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.overall-noise-scale=1.0',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.dof-pos=0.20',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.dof-vel=0.35',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-pos=[0.08,0.08,0.025]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-rot=[0.15,0.15,0.30]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-lin-vel=[0.20,0.20,0.10]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-ang-vel=[0.25,0.25,0.35]',
    '--command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.object-pos=[0.08,0.08,0.0]',
    '--command.setup-terms.motion-command.params.motion-config.enable-default-pose-prepend=True',
    '--command.setup-terms.motion-command.params.motion-config.default-pose-prepend-duration-s=0.2',
    '--command.setup-terms.motion-command.params.motion-config.enable-default-pose-append=True',
    '--command.setup-terms.motion-command.params.motion-config.default-pose-append-duration-s=2.0',
    '--command.setup-terms.motion-command.params.motion-config.contact-interval-runtime-prepend-compensation=False',
    '--reward.terms.offline-contact-guidance.weight=0.0',
    '--perception.camera-apply-sensor-noise=True',
    '--perception.camera-warp-edge-noise=True',
    '--perception.camera-warp-enable-holes=True',
    '--perception.camera-warp-hole-prob=0.2',
    '--perception.camera-warp-additive-noise-std=0.03',
    '--perception.camera-warp-depth-offset-std=0.03',
    '--perception.object-geometry-mode=mesh',
    '--perception.sensor-offset=[0.0576235,0.01753,0.42987]',
    '--perception.camera-mount-quat=[0.0,0.40354529635239006,0.0,0.9149596678498247]',
    '--perception.camera-frame-quat=[-0.5,0.5,-0.5,0.5]',
    '--robot.object.enabled=True',
    '--robot.object.object-urdf-path=${TEACHER_MOTION_BANK}/_clip_object_urdf_map.json',
    '--simulator.config.scene.env-spacing=5.0',
    '--simulator.config.sim.max-episode-length-s=10.0',
    '--simulator.config.sim.physx.gpu-found-lost-pairs-capacity=335544320',
    '--simulator.config.sim.physx.gpu-found-lost-aggregate-pairs-capacity=469762048',
    '--simulator.config.sim.physx.gpu-total-aggregate-pairs-capacity=83886080',
    '--simulator.config.sim.physx.gpu-collision-stack-size=268435456',
    '--logger.entity=${WANDB_ENTITY}',
    '--logger.name=${RUN_NAME}',
    '--logger.mode=online',
    '--logger.video.enabled=False',
    '--logger.headless-recording=False',
    '--logger.video.upload-to-wandb=False',
    '--logger.base-dir=${LOG_DIR}',
    '--logger.resume=never',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-button-window-mode=peak_height',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-peak-height-alpha=0.91',
    '--command.setup-terms.motion-command.params.motion-config.contact-aware-peak-height-smoothing-steps=5',
]

ENVIRONMENT = {
    'CUBLAS_WORKSPACE_CONFIG': ':4096:8',
    'CUDA_DEVICE_ORDER': 'PCI_BUS_ID',
    'HOLOSOMA_ACTIVATE_OBJECT_CONTACT_SENSORS': '0',
    'HOLOSOMA_ALLOW_LEGACY_OBJECT_URDF_FALLBACK': '0',
    'HOLOSOMA_CONTIGUOUS_MINIBATCHES': '1',
    'HOLOSOMA_DISABLE_AUTO_RESET': '0',
    'HOLOSOMA_DISABLE_CLIP_END_RESET': '0',
    'HOLOSOMA_DISABLE_MOTION_END_RESET': '0',
    'HOLOSOMA_EXTERNAL_AS_SINGLE_SLOT_DIR': '${TEACHER_MOTION_BANK}',
    'HOLOSOMA_EXTERNAL_AS_WORLD_SIZE': '${WORLD_SIZE}',
    'HOLOSOMA_GLOO_BARRIER': '1',
    'HOLOSOMA_GLOO_GRAD_REDUCE': '0',
    'HOLOSOMA_GLOO_SMALL_COLLECTIVES': '1',
    'HOLOSOMA_HIERARCHICAL_GRAD_REDUCE': '1',
    'HOLOSOMA_HIERARCHICAL_GRAD_REDUCE_CPU_LEADER': '1',
    'HOLOSOMA_HIERARCHICAL_PG_TIMEOUT_SEC': '300',
    'HOLOSOMA_HIERARCHICAL_SMALL_COLLECTIVES': '0',
    'HOLOSOMA_MINIBATCH_THROUGHPUT_CANARY': '0',
    'HOLOSOMA_MOTION_METRICS_INTERVAL': '16',
    'HOLOSOMA_OBJECT_COLLIDER_TYPE': 'convex_decomposition',
    'HOLOSOMA_OBJECT_SPAWN_MODE': 'single_slot_multi_urdf',
    'HOLOSOMA_PERCEPTION_INCLUDE_ROBOT_MESH': '1',
    'HOLOSOMA_PERCEPTION_INJECT_INTO_POLICY_MODULES': 'False',
    'HOLOSOMA_PERCEPTION_OBJECT_GEOMETRY_MODE': 'mesh',
    'HOLOSOMA_RANK_LOCAL_CPU_AFFINITY': '1',
    'HOLOSOMA_RANK_LOCAL_SHARDING_ENABLED': '1',
    'HOLOSOMA_RANK_VISIBLE_DEVICES': '1',
    'HOLOSOMA_REQUIRE_CONTACT_INTERVAL_COVERAGE': '0',
    'HOLOSOMA_REQUIRE_CONTACT_TARGET_COVERAGE': '0',
    'HOLOSOMA_REQUIRE_OBJECT_MESH_ASSETS': '1',
    'HOLOSOMA_REQUIRE_RANK_LOCAL_SHARD_PROVENANCE': '1',
    'HOLOSOMA_REQUIRE_SINGLE_SLOT_OBJECTS': '1',
    'HOLOSOMA_REQUIRE_WANDB_RUN': '1',
    'HOLOSOMA_SHARD_OBJECT_ASSETS_BY_RANK': '0',
    'HOLOSOMA_SKIP_INITIAL_CHECKPOINT': '1',
    'HOLOSOMA_SYNC_AFTER_GRAD_ALLREDUCE': '0',
    'HOLOSOMA_SYNC_AFTER_OPTIMIZER_STEP': '0',
    'HOLOSOMA_SYNC_BEFORE_GRAD_ALLREDUCE': '1',
    'NNODES': '${NODES}',
    'NPROC': '${NPROC}',
    'OMP_NUM_THREADS': '1',
    'PYTHONDONTWRITEBYTECODE': '1',
    'PYTHONHASHSEED': '0',
    'PYTHONNOUSERSITE': '1',
    'PYTORCH_CUDA_ALLOC_CONF': 'expandable_segments:True',
    'TORCH_ALLOW_TF32_CUBLAS_OVERRIDE': '1',
    'TORCH_DIST_BACKEND': 'gloo',
    'TORCH_DIST_TIMEOUT_SEC': '1800',
    'WANDB_CONSOLE': 'off',
    'WANDB_ENTITY': '${WANDB_ENTITY}',
    'WANDB_MODE': 'online',
    'WANDB_PROJECT': '${WANDB_PROJECT}',
    'WANDB_RESUME': 'never',
}

if __name__ == "__main__":
    launch("teacher", CLI, ENVIRONMENT, nodes=1)
