#!/usr/bin/env python3
from __future__ import annotations

import argparse
from contextlib import contextmanager
import ctypes
from dataclasses import dataclass
import fcntl
import hashlib
import json
import mmap
import os
import re
import shlex
import shutil
import stat
import struct
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any
from urllib.parse import unquote


_MARKER_NAME = ".generated_by_prepare_as_rank_shards"
_MARKER_BYTES = b"generated by prepare_as_rank_shards.py\n"
_MANIFEST_VERSION = 3
_SEALED_FILE_MODE = 0o444
_SEALED_DIRECTORY_MODE = 0o555
_PRIVATE_DIRECTORY_MODE = 0o700
MOTION_TRANSITION_SOURCE_KEY = "motion_transition_source"
MOTION_TRANSITION_SOURCE_VERSION = 1
_MOTION_TRANSITION_SOURCE_SEMANTICS = {
    "single_clip_static",
    "global_multi_clip_runtime",
}
_RENAME_EXCHANGE = 2
_AT_FDCWD = -100
_REMOTE_ASSET_PREFIXES = ("http://", "https://", "s3://", "omniverse://", "package://")
_MTL_TEXTURE_DIRECTIVES = {
    "bump",
    "decal",
    "disp",
    "map_bump",
    "map_d",
    "map_ka",
    "map_kd",
    "map_ke",
    "map_ks",
    "map_ns",
    "norm",
    "refl",
}
_OBJ_MTLLIB_RE = re.compile(rb"(?im)^[ \t]*mtllib(?:[ \t]+[^\r\n]*)?(?=\r?$)")
_ENTRY_SINGLE_MESH_KEYS = (
    "object_mesh_path",
    "object_visual_mesh_path",
    "object_collision_mesh_path",
)
_ENTRY_MULTI_MESH_KEYS = (
    "object_mesh_paths",
    "object_visual_mesh_paths",
    "object_collision_mesh_paths",
)


@dataclass(frozen=True)
class ClipSpec:
    clip_id: str
    npz_path: Path
    entry: dict[str, Any]
    urdf_paths: tuple[Path, ...]
    motion_weight: float
    urdf_weight: float


@dataclass(frozen=True)
class AssignmentUnit:
    unit_id: str
    clip_ids: tuple[str, ...]
    urdf_paths: tuple[str, ...]
    weight: float


@dataclass(frozen=True)
class RankShardFilePlan:
    """Exact bytes and links for one source-derived rank-local view."""

    rank: int
    rank_units: tuple[AssignmentUnit, ...]
    clip_ids: tuple[str, ...]
    object_map_bytes: bytes
    clip_ids_bytes: bytes
    npz_sources: tuple[Path, ...]
    npz_link_targets: tuple[str, ...]
    shard_record: dict[str, Any]


@dataclass(frozen=True)
class RankShardPlan:
    """Deterministic published tree derived without trusting an existing root."""

    manifest: dict[str, Any]
    rank_files: tuple[RankShardFilePlan, ...]


class _SourceScanGuard:
    """Keep one source-digest pass on a single fail-closed filesystem view."""

    def __init__(self) -> None:
        self._files: dict[
            Path,
            tuple[
                Path,
                tuple[int, int, int, int, int],
                tuple[int, int, int, int, int],
            ],
        ] = {}
        self._motion_listings: dict[
            Path,
            tuple[Path, tuple[int, int], tuple[int, int], tuple[str, ...]],
        ] = {}

    @staticmethod
    def _logical_path(path: Path) -> Path:
        # Keep ``..`` and symlink-bearing components in the lexical path.  A
        # later verification must resolve the exact reference consumed by the
        # parser again; normalizing it to the current target here would make a
        # symlink retarget invisible to the guard.
        expanded = path.expanduser()
        return expanded if expanded.is_absolute() else Path.cwd() / expanded

    def record(self, path: Path) -> None:
        logical = self._logical_path(path)
        try:
            logical_stat = logical.lstat()
            resolved = logical.resolve(strict=True)
            stat_result = resolved.stat()
        except FileNotFoundError as exc:
            raise RuntimeError(
                f"Rank-shard source disappeared while its snapshot was being computed: {logical}"
            ) from exc
        if not resolved.is_file():
            raise FileNotFoundError(f"Expected a regular rank-shard source file: {resolved}")
        # Preserve both the lexical entry and the resolved target.  Otherwise
        # a source symlink could be retargeted during parsing and later point
        # back at the original inode before the final verification.
        current = (
            resolved,
            _stat_identity(logical_stat),
            _stat_identity(stat_result),
        )
        expected = self._files.setdefault(logical, current)
        if current != expected:
            raise RuntimeError(
                "Rank-shard source changed while its dependency snapshot was being computed: "
                f"{logical}"
            )

    def record_motion_listing(self, motion_dir: Path, paths: list[Path] | tuple[Path, ...]) -> None:
        logical_root = self._logical_path(motion_dir)
        current = self._motion_listing_view(logical_root, paths)
        expected = self._motion_listings.setdefault(logical_root, current)
        if current != expected:
            raise RuntimeError(
                "Rank-shard motion-file listing changed while its source snapshot was being computed: "
                f"{logical_root}"
            )

    def _motion_listing_view(
        self,
        logical_root: Path,
        paths: list[Path] | tuple[Path, ...],
    ) -> tuple[Path, tuple[int, int], tuple[int, int], tuple[str, ...]]:
        try:
            logical_stat = logical_root.lstat()
            resolved_root = logical_root.resolve(strict=True)
            resolved_stat = resolved_root.stat()
        except FileNotFoundError as exc:
            raise RuntimeError(
                "Rank-shard motion directory disappeared while its source snapshot was being computed: "
                f"{logical_root}"
            ) from exc
        if not resolved_root.is_dir():
            raise NotADirectoryError(f"Expected a rank-shard motion directory: {logical_root}")

        relative_names: list[str] = []
        for path in paths:
            logical_path = self._logical_path(path)
            try:
                resolved_parent = logical_path.parent.resolve(strict=True)
            except FileNotFoundError as exc:
                raise RuntimeError(
                    "Rank-shard motion-file parent disappeared while its source snapshot was being computed: "
                    f"{logical_path}"
                ) from exc
            if resolved_parent != resolved_root:
                raise RuntimeError(
                    "Rank-shard motion-file listing escaped its motion directory: "
                    f"root={logical_root}, path={logical_path}"
                )
            relative_names.append(logical_path.name)
        return (
            resolved_root,
            (int(logical_stat.st_dev), int(logical_stat.st_ino)),
            (int(resolved_stat.st_dev), int(resolved_stat.st_ino)),
            tuple(sorted(relative_names)),
        )

    def verify(self) -> None:
        for logical in tuple(self._files):
            self.record(logical)
        for logical_root, expected in self._motion_listings.items():
            actual = self._motion_listing_view(
                logical_root,
                list(logical_root.glob("*.npz")),
            )
            if actual != expected:
                raise RuntimeError(
                    "Rank-shard motion-file listing changed while its source snapshot was being computed: "
                    f"{logical_root}"
                )


def _resolve_path(raw: str, base_dir: Path) -> Path:
    path = Path(str(raw).strip()).expanduser()
    if path.is_absolute():
        return path
    return base_dir / path


def _relpath(path: Path, base_dir: Path) -> str:
    return os.path.relpath(path.resolve(), base_dir.resolve())


def _stat_identity(stat_result: os.stat_result) -> tuple[int, int, int, int, int]:
    return (
        int(stat_result.st_dev),
        int(stat_result.st_ino),
        int(stat_result.st_size),
        int(stat_result.st_mtime_ns),
        # A writer can replace bytes in place, preserve the file size, and
        # restore mtime with os.utime().  ctime still changes for an ordinary
        # filesystem write, closing that parse-before-hash drift window.
        int(stat_result.st_ctime_ns),
    )


def _stable_file_digest(path: Path) -> tuple[str, int, Path]:
    resolved = path.resolve(strict=True)
    before = resolved.stat()
    if not resolved.is_file():
        raise FileNotFoundError(f"Expected a regular file: {resolved}")
    digest = hashlib.sha256()
    with resolved.open("rb") as stream:
        for chunk in iter(lambda: stream.read(4 * 1024 * 1024), b""):
            digest.update(chunk)
    after = resolved.stat()
    if _stat_identity(before) != _stat_identity(after):
        raise RuntimeError(f"File changed while being hashed: {resolved}")
    return digest.hexdigest(), int(after.st_size), resolved


def _sha256_file(path: Path) -> str:
    return _stable_file_digest(path)[0]


def _sha256_json(value: Any) -> str:
    encoded = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _file_record(path: Path) -> dict[str, Any]:
    digest, size, _ = _stable_file_digest(path)
    return {
        "name": path.name,
        "size": size,
        "sha256": digest,
    }


def _source_file_record(path: Path) -> dict[str, Any]:
    digest, size, resolved = _stable_file_digest(path)
    return {
        "path": str(resolved),
        "size": size,
        "sha256": digest,
    }


def _load_clip_map(path: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict) and isinstance(payload.get("clips"), dict):
        return {key: value for key, value in payload.items() if key != "clips"}, payload["clips"]
    if isinstance(payload, dict):
        return {}, payload
    raise ValueError(f"Invalid object map: {path}")


def canonical_motion_transition_source(
    value: Any,
    *,
    active_clip_count: int,
    role: str,
) -> dict[str, Any]:
    """Validate the content-bound timeline lineage independently of the objective.

    ``source_clip_count`` describes the bank whose transition implementation
    the active view inherits.  It deliberately does *not* describe the clips
    in the current optimization objective; rank-local ``global_clip_count``
    retains that separate meaning.
    """

    if not isinstance(value, dict):
        raise ValueError(f"{role} must be a JSON object")
    expected_keys = {"version", "source_clip_count", "source_semantics"}
    if set(value) != expected_keys:
        raise ValueError(
            f"{role} must contain exactly {sorted(expected_keys)}, got {sorted(map(str, value))}"
        )
    version = value.get("version")
    if type(version) is not int or version != MOTION_TRANSITION_SOURCE_VERSION:
        raise ValueError(
            f"{role}.version must be the integer {MOTION_TRANSITION_SOURCE_VERSION}, got {version!r}"
        )
    source_clip_count = value.get("source_clip_count")
    if type(source_clip_count) is not int or source_clip_count <= 0:
        raise ValueError(f"{role}.source_clip_count must be a positive integer")
    if type(active_clip_count) is not int or active_clip_count <= 0:
        raise ValueError(f"{role} active_clip_count must be a positive integer")
    if source_clip_count < active_clip_count:
        raise ValueError(
            f"{role}.source_clip_count={source_clip_count} is smaller than the active clip count "
            f"{active_clip_count}"
        )
    source_semantics = value.get("source_semantics")
    if source_semantics not in _MOTION_TRANSITION_SOURCE_SEMANTICS:
        raise ValueError(
            f"{role}.source_semantics must be one of "
            f"{sorted(_MOTION_TRANSITION_SOURCE_SEMANTICS)}, got {source_semantics!r}"
        )
    expected_semantics = (
        "single_clip_static" if source_clip_count == 1 else "global_multi_clip_runtime"
    )
    if source_semantics != expected_semantics:
        raise ValueError(
            f"{role} is internally inconsistent: source_clip_count={source_clip_count} requires "
            f"source_semantics={expected_semantics!r}, got {source_semantics!r}"
        )
    return {
        "version": MOTION_TRANSITION_SOURCE_VERSION,
        "source_clip_count": source_clip_count,
        "source_semantics": source_semantics,
    }


def resolve_motion_transition_source(
    metadata: dict[str, Any],
    *,
    active_clip_count: int,
    infer_if_missing: bool,
    role: str,
) -> dict[str, Any] | None:
    raw = metadata.get(MOTION_TRANSITION_SOURCE_KEY)
    if raw is None:
        if not infer_if_missing:
            return None
        raw = {
            "version": MOTION_TRANSITION_SOURCE_VERSION,
            "source_clip_count": active_clip_count,
            "source_semantics": (
                "single_clip_static"
                if active_clip_count == 1
                else "global_multi_clip_runtime"
            ),
        }
    return canonical_motion_transition_source(
        raw,
        active_clip_count=active_clip_count,
        role=role,
    )


def _motion_weight(path: Path) -> float:
    try:
        size_mb = path.stat().st_size / (1024.0 * 1024.0)
    except OSError:
        size_mb = 0.0
    return 1.0 + size_mb / 128.0


def _mesh_file_size_mb(
    raw: str,
    base_dir: Path,
    *,
    source_guard: _SourceScanGuard | None = None,
) -> float:
    if not raw or raw.startswith(("package://", "http://", "https://", "file://")):
        return 0.0
    try:
        path = _resolve_path(raw, base_dir)
        if not path.is_file():
            return 0.0
        if source_guard is not None:
            source_guard.record(path)
        return path.stat().st_size / (1024.0 * 1024.0)
    except OSError:
        return 0.0


def _urdf_weight(path: Path, *, source_guard: _SourceScanGuard | None = None) -> float:
    if source_guard is not None:
        source_guard.record(path)
    try:
        root = ET.parse(path).getroot()
    except Exception:
        return 1.0

    collision_count = len(root.findall(".//collision"))
    visual_count = len(root.findall(".//visual"))
    mesh_size_mb = 0.0
    seen_meshes: set[str] = set()
    for mesh in root.findall(".//mesh"):
        filename = str(mesh.get("filename", "")).strip()
        if filename in seen_meshes:
            continue
        seen_meshes.add(filename)
        mesh_size_mb += _mesh_file_size_mb(
            filename,
            path.parent,
            source_guard=source_guard,
        )

    return 1.0 + 2.0 * collision_count + 0.5 * visual_count + mesh_size_mb / 8.0


def _normalize_entry(raw_entry: Any) -> dict[str, Any]:
    if isinstance(raw_entry, dict):
        return dict(raw_entry)
    return {"object_urdf_path": str(raw_entry)}


def _as_string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, (list, tuple)):
        return [str(item) for item in value]
    return [str(value)]


def _entry_urdf_paths(entry: dict[str, Any], *, base_dir: Path) -> tuple[Path, ...]:
    raw_paths: list[str] = []
    raw_paths.extend(_as_string_list(entry.get("object_urdf_path")))
    raw_paths.extend(_as_string_list(entry.get("object_urdf_paths")))
    raw_paths.extend(_as_string_list(entry.get("object_urdfs")))

    resolved: list[Path] = []
    seen: set[Path] = set()
    for raw in raw_paths:
        raw = str(raw).strip()
        if not raw:
            continue
        urdf_path = _resolve_path(raw, base_dir)
        if urdf_path in seen:
            continue
        seen.add(urdf_path)
        resolved.append(urdf_path)
    return tuple(resolved)


def _active_clip_specs(
    *,
    motion_dir: Path,
    object_map: Path,
    source_guard: _SourceScanGuard | None = None,
) -> tuple[dict[str, Any], list[ClipSpec]]:
    if source_guard is not None:
        source_guard.record(object_map)
    metadata, clips = _load_clip_map(object_map)
    if not clips:
        raise ValueError(f"Object map has no clips: {object_map}")

    npz_paths = sorted(motion_dir.glob("*.npz"))
    if source_guard is not None:
        source_guard.record_motion_listing(motion_dir, npz_paths)
        for path in npz_paths:
            source_guard.record(path)
    npz_by_clip = {path.stem: path for path in npz_paths}
    if not npz_by_clip:
        raise FileNotFoundError(f"No .npz clips found under motion dir: {motion_dir}")

    missing_map_entries = sorted(set(npz_by_clip).difference(clips))
    if missing_map_entries:
        preview = ", ".join(missing_map_entries[:10])
        raise ValueError(
            f"Object map is missing {len(missing_map_entries)} active clip(s) from {motion_dir}: {preview}"
        )

    urdf_weights: dict[Path, float] = {}
    specs: list[ClipSpec] = []
    for clip_id in sorted(npz_by_clip):
        entry = _normalize_entry(clips[clip_id])
        urdf_paths = _entry_urdf_paths(entry, base_dir=object_map.parent)
        if not urdf_paths:
            raise ValueError(f"Clip '{clip_id}' has no object URDF dependency")
        for urdf_path in urdf_paths:
            if not urdf_path.is_file():
                raise FileNotFoundError(f"Clip '{clip_id}' object URDF is missing: {urdf_path}")
            if urdf_path not in urdf_weights:
                urdf_weights[urdf_path] = _urdf_weight(
                    urdf_path,
                    source_guard=source_guard,
                )
        specs.append(
            ClipSpec(
                clip_id=clip_id,
                npz_path=npz_by_clip[clip_id],
                entry=entry,
                urdf_paths=urdf_paths,
                motion_weight=_motion_weight(npz_by_clip[clip_id]),
                urdf_weight=sum(urdf_weights[urdf_path] for urdf_path in urdf_paths),
            )
        )
    transition_source = resolve_motion_transition_source(
        metadata,
        active_clip_count=len(specs),
        infer_if_missing=True,
        role=f"object map {object_map} {MOTION_TRANSITION_SOURCE_KEY}",
    )
    assert transition_source is not None
    metadata = dict(metadata)
    metadata[MOTION_TRANSITION_SOURCE_KEY] = transition_source
    return metadata, specs


def _resolve_dependency(raw: str, *, base_dir: Path, role: str) -> Path:
    reference = str(raw).strip()
    if not reference:
        raise ValueError(f"{role} has an empty asset reference")
    lowered = reference.lower()
    if lowered.startswith(_REMOTE_ASSET_PREFIXES) or lowered.startswith("data:"):
        raise ValueError(f"{role} uses an unsupported non-local asset reference: {reference!r}")
    if lowered.startswith("file://"):
        reference = unquote(reference[len("file://") :])
    path = Path(reference).expanduser()
    if not path.is_absolute():
        path = base_dir / path
    if not path.is_file():
        raise FileNotFoundError(f"{role} dependency does not exist: {path}")
    return path


def _shell_words(line: str, *, role: str) -> list[str]:
    try:
        return shlex.split(line, comments=True, posix=True)
    except ValueError as exc:
        raise ValueError(f"{role} contains an invalid quoted asset reference: {line!r}") from exc


def _glb_json_payload(mesh_path: Path) -> dict[str, Any]:
    file_size = mesh_path.stat().st_size
    with mesh_path.open("rb") as stream:
        header = stream.read(12)
        if len(header) != 12:
            raise ValueError(f"GLB header is truncated: {mesh_path}")
        magic, version, declared_length = struct.unpack("<4sII", header)
        if magic != b"glTF" or version != 2:
            raise ValueError(
                f"Unsupported GLB header at {mesh_path}: magic={magic!r}, version={version}"
            )
        if declared_length != file_size:
            raise ValueError(
                f"GLB declared length does not match file size at {mesh_path}: "
                f"declared={declared_length}, actual={file_size}"
            )
        if declared_length % 4 != 0:
            raise ValueError(f"GLB file length is not 4-byte aligned: {mesh_path}")
        chunk_header = stream.read(8)
        if len(chunk_header) != 8:
            raise ValueError(f"GLB has no complete JSON chunk: {mesh_path}")
        json_length, json_type = struct.unpack("<II", chunk_header)
        if json_type != 0x4E4F534A or json_length <= 0:
            raise ValueError(f"GLB first chunk is not a non-empty JSON chunk: {mesh_path}")
        if json_length % 4 != 0:
            raise ValueError(f"GLB JSON chunk is not 4-byte aligned: {mesh_path}")
        json_bytes = stream.read(json_length)
        if len(json_bytes) != json_length:
            raise ValueError(f"GLB JSON chunk is truncated: {mesh_path}")
        offset = 20 + json_length
        while offset < declared_length:
            remaining_header = stream.read(8)
            if len(remaining_header) != 8:
                raise ValueError(f"GLB chunk header is truncated: {mesh_path}")
            chunk_length, _chunk_type = struct.unpack("<II", remaining_header)
            if chunk_length % 4 != 0:
                raise ValueError(f"GLB chunk is not 4-byte aligned: {mesh_path}")
            offset += 8 + chunk_length
            if offset > declared_length:
                raise ValueError(f"GLB chunk exceeds declared file length: {mesh_path}")
            stream.seek(chunk_length, os.SEEK_CUR)
        if offset != declared_length or stream.tell() != declared_length:
            raise ValueError(f"GLB chunk table does not close at the file boundary: {mesh_path}")
    try:
        payload = json.loads(json_bytes.rstrip(b" \t\r\n\x00").decode("utf-8", errors="strict"))
    except Exception as exc:
        raise ValueError(f"Invalid GLB JSON at {mesh_path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"GLB JSON root must be an object: {mesh_path}")
    return payload


def _collect_gltf_dependency_paths(payload: dict[str, Any], *, mesh_path: Path) -> list[Path]:
    for collection_name in ("buffers", "images"):
        collection = payload.get(collection_name, [])
        if not isinstance(collection, list):
            raise ValueError(f"glTF {collection_name} must be a list: {mesh_path}")
        if any(not isinstance(entry, dict) for entry in collection):
            raise ValueError(f"glTF {collection_name} entries must be objects: {mesh_path}")

    paths: list[Path] = []
    for field_path, raw_uri in _gltf_uri_fields(payload):
        if not isinstance(raw_uri, str):
            raise ValueError(
                f"glTF URI field {_format_json_path(field_path)} must be a string: {mesh_path}"
            )
        uri = raw_uri.strip()
        if uri.lower().startswith("data:"):
            continue
        paths.append(
            _resolve_dependency(
                unquote(uri),
                base_dir=mesh_path.parent,
                role=f"glTF {mesh_path}{_format_json_path(field_path)}",
            )
        )
    return paths


def _gltf_uri_fields(
    value: Any,
    path: tuple[str | int, ...] = (),
) -> list[tuple[tuple[str | int, ...], Any]]:
    fields: list[tuple[tuple[str | int, ...], Any]] = []
    if isinstance(value, dict):
        for key, child in value.items():
            child_path = (*path, str(key))
            if str(key).lower() == "uri":
                fields.append((child_path, child))
            else:
                fields.extend(_gltf_uri_fields(child, child_path))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            fields.extend(_gltf_uri_fields(child, (*path, index)))
    return fields


def _format_json_path(path: tuple[str | int, ...]) -> str:
    return "".join(f"[{item}]" if isinstance(item, int) else f".{item}" for item in path)


def collect_local_mesh_asset_paths(
    mesh_path: Path,
    *,
    source_guard: _SourceScanGuard | None = None,
) -> tuple[Path, ...]:
    """Return the complete local file closure for one supported mesh asset."""

    mesh_path = _SourceScanGuard._logical_path(mesh_path)
    if not mesh_path.is_file():
        raise FileNotFoundError(f"Mesh asset does not exist: {mesh_path}")
    if source_guard is not None:
        source_guard.record(mesh_path)
    paths: list[Path] = [mesh_path]
    suffix = mesh_path.suffix.lower()
    if suffix == ".stl":
        return tuple(paths)
    if suffix == ".obj":
        material_paths: list[Path] = []
        with mesh_path.open("rb") as stream:
            if mesh_path.stat().st_size:
                with mmap.mmap(stream.fileno(), 0, access=mmap.ACCESS_READ) as mapped:
                    for match in _OBJ_MTLLIB_RE.finditer(mapped):
                        try:
                            line = match.group(0).decode("utf-8", errors="strict")
                        except UnicodeDecodeError as exc:
                            raise ValueError(f"OBJ mtllib directive is not valid UTF-8: {mesh_path}") from exc
                        words = _shell_words(line, role=f"OBJ {mesh_path}")
                        if len(words) < 2:
                            raise ValueError(f"OBJ has an empty mtllib directive: {mesh_path}")
                        material_paths.extend(
                            _resolve_dependency(
                                reference,
                                base_dir=mesh_path.parent,
                                role=f"OBJ {mesh_path} material",
                            )
                            for reference in words[1:]
                        )
        for material_path in material_paths:
            paths.append(material_path)
            if source_guard is not None:
                source_guard.record(material_path)
            try:
                material_lines = material_path.read_text(encoding="utf-8", errors="strict").splitlines()
            except UnicodeDecodeError as exc:
                raise ValueError(f"MTL is not valid UTF-8: {material_path}") from exc
            for line in material_lines:
                stripped = line.lstrip()
                directive = stripped.split(maxsplit=1)[0].lower() if stripped else ""
                if not directive or (
                    directive not in _MTL_TEXTURE_DIRECTIVES and not directive.startswith("map_")
                ):
                    continue
                words = _shell_words(line, role=f"MTL {material_path}")
                if len(words) < 2:
                    raise ValueError(f"MTL has an empty texture directive: {material_path}")
                paths.append(
                    _resolve_dependency(
                        words[-1],
                        base_dir=material_path.parent,
                        role=f"MTL {material_path} texture",
                    )
                )
    elif suffix in {".gltf", ".glb"}:
        if suffix == ".glb":
            payload = _glb_json_payload(mesh_path)
        else:
            try:
                payload = json.loads(mesh_path.read_text(encoding="utf-8"))
            except Exception as exc:
                raise ValueError(f"Invalid glTF JSON at {mesh_path}: {exc}") from exc
            if not isinstance(payload, dict):
                raise ValueError(f"glTF root must be an object: {mesh_path}")
        paths.extend(_collect_gltf_dependency_paths(payload, mesh_path=mesh_path))
    elif suffix == ".dae":
        try:
            root = ET.parse(mesh_path).getroot()
        except Exception as exc:
            raise ValueError(f"Invalid COLLADA XML at {mesh_path}: {exc}") from exc
        _reject_external_collada_document_references(root, mesh_path=mesh_path)
        image_index = 0
        for image in root.iter():
            if image.tag.rsplit("}", 1)[-1] != "image":
                continue
            init_from_nodes = [
                element
                for element in image.iter()
                if element.tag.rsplit("}", 1)[-1] == "init_from"
            ]
            if not init_from_nodes:
                raise ValueError(f"COLLADA image has no init_from element: {mesh_path}")
            for element in init_from_nodes:
                reference = (element.text or "").strip()
                if not reference:
                    raise ValueError(f"COLLADA image has an empty init_from element: {mesh_path}")
                if reference.startswith("#"):
                    raise ValueError(
                        f"COLLADA image uses an unsupported internal reference {reference!r}: {mesh_path}"
                    )
                if not reference.lower().startswith("data:"):
                    paths.append(
                        _resolve_dependency(
                            reference,
                            base_dir=mesh_path.parent,
                            role=f"COLLADA {mesh_path} texture[{image_index}]",
                        )
                    )
                image_index += 1
    elif suffix == ".ply":
        with mesh_path.open("rb") as stream:
            header = stream.read(1024 * 1024)
        marker_index = header.find(b"end_header")
        if marker_index < 0:
            raise ValueError(f"PLY header has no end_header marker: {mesh_path}")
        try:
            header_text = header[:marker_index].decode("ascii")
        except UnicodeDecodeError as exc:
            raise ValueError(f"PLY header is not ASCII: {mesh_path}") from exc
        for index, line in enumerate(header_text.splitlines()):
            words = line.strip().split(maxsplit=2)
            if len(words) == 3 and words[0].lower() == "comment" and words[1].lower() == "texturefile":
                paths.append(
                    _resolve_dependency(
                        words[2],
                        base_dir=mesh_path.parent,
                        role=f"PLY {mesh_path} texture[{index}]",
                    )
                )
    else:
        raise ValueError(
            f"Mesh format {suffix or '<none>'!r} has no implemented transitive dependency closure: {mesh_path}"
        )
    if source_guard is not None:
        for path in paths:
            source_guard.record(path)
    return tuple(dict.fromkeys(paths))


def _reject_external_collada_document_references(root: ET.Element, *, mesh_path: Path) -> None:
    for element in root.iter():
        element_name = element.tag.rsplit("}", 1)[-1].lower()
        for raw_name, raw_value in element.attrib.items():
            attribute_name = raw_name.rsplit("}", 1)[-1].lower()
            is_document_reference = attribute_name in {"url", "href"} or (
                attribute_name == "source" and element_name in {"skin", "morph"}
            )
            if not is_document_reference:
                continue
            reference = str(raw_value).strip()
            if reference and not reference.startswith("#"):
                raise ValueError(
                    "COLLADA external document references are unsupported for content closure: "
                    f"reference={reference!r}, element=<{element_name}>, path={mesh_path}"
                )


def collect_local_urdf_asset_paths(
    urdf_path: Path,
    *,
    mesh_cache: dict[Path, tuple[Path, ...]] | None = None,
    source_guard: _SourceScanGuard | None = None,
) -> tuple[Path, ...]:
    """Return the URDF, every mesh, and every transitive local dependency."""

    urdf_path = _SourceScanGuard._logical_path(urdf_path)
    if not urdf_path.is_file():
        raise FileNotFoundError(f"URDF asset does not exist: {urdf_path}")
    if source_guard is not None:
        source_guard.record(urdf_path)
    try:
        root = ET.parse(urdf_path).getroot()
    except Exception as exc:
        raise ValueError(f"Invalid URDF XML at {urdf_path}: {exc}") from exc
    paths: list[Path] = [urdf_path]
    for index, mesh in enumerate(root.findall(".//mesh")):
        mesh_path = _resolve_dependency(
            str(mesh.get("filename", "")),
            base_dir=urdf_path.parent,
            role=f"URDF {urdf_path} mesh[{index}]",
        )
        mesh_assets = mesh_cache.get(mesh_path) if mesh_cache is not None else None
        if mesh_assets is None:
            mesh_assets = collect_local_mesh_asset_paths(
                mesh_path,
                source_guard=source_guard,
            )
            if mesh_cache is not None:
                mesh_cache[mesh_path] = mesh_assets
        paths.extend(mesh_assets)
    for index, texture in enumerate(root.findall(".//texture")):
        paths.append(
            _resolve_dependency(
                str(texture.get("filename", "")),
                base_dir=urdf_path.parent,
                role=f"URDF {urdf_path} texture[{index}]",
            )
        )
    if source_guard is not None:
        for path in paths:
            source_guard.record(path)
    return tuple(dict.fromkeys(paths))


def _local_entry_mesh_paths(
    entry: dict[str, Any],
    *,
    base_dir: Path,
    mesh_cache: dict[Path, tuple[Path, ...]] | None = None,
    source_guard: _SourceScanGuard | None = None,
) -> tuple[Path, ...]:
    raw_paths: list[str] = []
    for key in (*_ENTRY_SINGLE_MESH_KEYS, *_ENTRY_MULTI_MESH_KEYS):
        raw_paths.extend(_as_string_list(entry.get(key)))
    paths: list[Path] = []
    for raw in raw_paths:
        raw = str(raw).strip()
        if not raw:
            continue
        path = _resolve_dependency(raw, base_dir=base_dir, role="object-map mesh")
        mesh_assets = mesh_cache.get(path) if mesh_cache is not None else None
        if mesh_assets is None:
            mesh_assets = collect_local_mesh_asset_paths(
                path,
                source_guard=source_guard,
            )
            if mesh_cache is not None:
                mesh_cache[path] = mesh_assets
        paths.extend(mesh_assets)
    return tuple(dict.fromkeys(paths))


def _rank_shard_source_digest_from_specs(
    *,
    motion_dir: Path,
    object_map: Path,
    specs: list[ClipSpec],
    world_size: int,
    environments_per_rank: int | None = None,
    source_guard: _SourceScanGuard | None = None,
) -> str:
    if source_guard is None:
        source_guard = _SourceScanGuard()
    source_guard.record(object_map)
    source_guard.record_motion_listing(motion_dir, [spec.npz_path for spec in specs])
    for spec in specs:
        source_guard.record(spec.npz_path)
    asset_path_set: set[Path] = set()
    mesh_cache: dict[Path, tuple[Path, ...]] = {}
    urdf_cache: dict[Path, tuple[Path, ...]] = {}
    for spec in specs:
        for urdf_path in spec.urdf_paths:
            urdf_assets = urdf_cache.get(urdf_path)
            if urdf_assets is None:
                urdf_assets = collect_local_urdf_asset_paths(
                    urdf_path,
                    mesh_cache=mesh_cache,
                    source_guard=source_guard,
                )
                urdf_cache[urdf_path] = urdf_assets
            asset_path_set.update(urdf_assets)
        asset_path_set.update(
            _local_entry_mesh_paths(
                spec.entry,
                base_dir=object_map.parent,
                mesh_cache=mesh_cache,
                source_guard=source_guard,
            )
        )
    # The guard retains every lexical reference so symlink/parent retargets are
    # detectable, while the content identity remains canonicalized by the
    # resolved consumer target.  A mesh commonly appears through the URDF plus
    # several equivalent object-map metadata paths; hashing duplicate lexical
    # spellings would change an existing scientific digest even though the
    # byte closure and the rank-local rewritten paths are unchanged.
    asset_paths = sorted({path.resolve(strict=True) for path in asset_path_set}, key=str)
    identity = {
        "schema": _MANIFEST_VERSION,
        "world_size": world_size,
        # Absolute paths are intentional: rank shard symlinks and rewritten
        # object-map paths are part of the published result.
        "motion_dir": str(motion_dir.resolve()),
        "object_map": _source_file_record(object_map),
        "motion_files": [_source_file_record(spec.npz_path) for spec in specs],
        "object_assets": [_source_file_record(path) for path in asset_paths],
    }
    if environments_per_rank is not None:
        identity["environments_per_rank"] = environments_per_rank
    source_guard.verify()
    return _sha256_json(identity)


def compute_rank_shard_source_digest(
    *,
    motion_dir: Path,
    object_map: Path,
    world_size: int,
    environments_per_rank: int | None = None,
) -> str:
    if world_size < 1:
        raise ValueError(f"world_size must be >= 1, got {world_size}")
    if environments_per_rank is not None and environments_per_rank < 1:
        raise ValueError(
            f"environments_per_rank must be >= 1, got {environments_per_rank}"
        )
    source_guard = _SourceScanGuard()
    _, specs = _active_clip_specs(
        motion_dir=motion_dir,
        object_map=object_map,
        source_guard=source_guard,
    )
    return _rank_shard_source_digest_from_specs(
        motion_dir=motion_dir,
        object_map=object_map,
        specs=specs,
        world_size=world_size,
        environments_per_rank=environments_per_rank,
        source_guard=source_guard,
    )


def _assignment_units(specs: list[ClipSpec], world_size: int) -> tuple[str, list[AssignmentUnit]]:
    specs_by_urdf: dict[tuple[str, ...], list[ClipSpec]] = {}
    for spec in specs:
        closure_key = tuple(str(path) for path in spec.urdf_paths)
        specs_by_urdf.setdefault(closure_key, []).append(spec)

    if len(specs_by_urdf) >= world_size:
        units: list[AssignmentUnit] = []
        for urdf_paths, group_specs in sorted(specs_by_urdf.items()):
            first = group_specs[0]
            units.append(
                AssignmentUnit(
                    unit_id="|".join(urdf_paths),
                    clip_ids=tuple(spec.clip_id for spec in sorted(group_specs, key=lambda item: item.clip_id)),
                    urdf_paths=urdf_paths,
                    weight=first.urdf_weight + sum(spec.motion_weight for spec in group_specs),
                )
            )
        return "object_closure", units

    units = [
        AssignmentUnit(
            unit_id=spec.clip_id,
            clip_ids=(spec.clip_id,),
            urdf_paths=tuple(str(path) for path in spec.urdf_paths),
            weight=spec.urdf_weight + spec.motion_weight,
        )
        for spec in specs
    ]
    return "clip", units


def _compatible_rank_clip_capacities(
    *,
    clip_count: int,
    world_size: int,
    environments_per_rank: int,
) -> list[int]:
    """Choose the most balanced exact clip counts that divide the env count."""

    if clip_count < world_size:
        raise ValueError(
            "Environment-compatible exact rank shards require at least one source clip "
            f"per rank, got clips={clip_count}, world_size={world_size}."
        )
    divisors = [
        value
        for value in range(1, min(clip_count, environments_per_rank) + 1)
        if environments_per_rank % value == 0
    ]
    target = clip_count / float(world_size)
    # sum -> (imbalance cost, capacities). The capacity tuple is also the
    # deterministic tie-breaker.
    states: dict[int, tuple[float, tuple[int, ...]]] = {0: (0.0, ())}
    for rank in range(world_size):
        next_states: dict[int, tuple[float, tuple[int, ...]]] = {}
        ranks_left = world_size - rank - 1
        for partial_sum, (cost, capacities) in states.items():
            for capacity in divisors:
                new_sum = partial_sum + capacity
                if new_sum + ranks_left > clip_count:
                    continue
                if new_sum + ranks_left * divisors[-1] < clip_count:
                    continue
                candidate = (
                    cost + (capacity - target) ** 2,
                    capacities + (capacity,),
                )
                current = next_states.get(new_sum)
                if current is None or candidate < current:
                    next_states[new_sum] = candidate
        states = next_states
    if clip_count not in states:
        raise ValueError(
            "Could not partition the clip bank into non-empty per-rank clip counts "
            "that all divide environments_per_rank: "
            f"clips={clip_count}, world_size={world_size}, "
            f"environments_per_rank={environments_per_rank}, divisors={divisors}."
        )
    # Put larger shards first so rank numbering is stable and obvious in the
    # manifest; the assignment itself still balances measured unit weights.
    return sorted(states[clip_count][1], reverse=True)


def _assign_units(
    units: list[AssignmentUnit],
    world_size: int,
    environments_per_rank: int | None = None,
) -> tuple[list[list[AssignmentUnit]], bool]:
    assignments: list[list[AssignmentUnit]] = [[] for _ in range(world_size)]
    rank_weights = [0.0 for _ in range(world_size)]

    rank_capacities: list[int] | None = None
    if environments_per_rank is not None:
        if any(len(unit.clip_ids) != 1 for unit in units):
            raise ValueError(
                "Environment-compatible rank sharding currently requires one clip per "
                "assignment unit; split shared object-closure units or omit "
                "--environments-per-rank."
            )
        if len(units) >= world_size:
            rank_capacities = _compatible_rank_clip_capacities(
                clip_count=len(units),
                world_size=world_size,
                environments_per_rank=environments_per_rank,
            )

    for unit in sorted(units, key=lambda item: (-item.weight, item.unit_id)):
        candidates = (
            range(world_size)
            if rank_capacities is None
            else (
                rank
                for rank in range(world_size)
                if len(assignments[rank]) < rank_capacities[rank]
            )
        )
        try:
            rank = min(
                candidates,
                key=lambda idx: (rank_weights[idx], len(assignments[idx]), idx),
            )
        except ValueError as exc:
            raise RuntimeError("Rank-shard capacity plan was exhausted early.") from exc
        assignments[rank].append(unit)
        rank_weights[rank] += unit.weight

    if rank_capacities is not None:
        actual = [len(rank_units) for rank_units in assignments]
        if actual != rank_capacities:
            raise RuntimeError(
                f"Rank-shard capacity plan mismatch: expected={rank_capacities}, actual={actual}."
            )

    duplicated = False
    empty_ranks = [rank for rank, rank_units in enumerate(assignments) if not rank_units]
    if empty_ranks:
        duplicated = True
        source_units = sorted(units, key=lambda item: (-item.weight, item.unit_id))
        for offset, rank in enumerate(empty_ranks):
            unit = source_units[offset % len(source_units)]
            assignments[rank].append(unit)
            rank_weights[rank] += unit.weight

    return assignments, duplicated


def _lexical_absolute_path(path: Path) -> Path:
    """Return an absolute normalized spelling without following symlinks."""

    expanded = path.expanduser()
    return Path(os.path.abspath(os.fspath(expanded)))


def _validate_output_path_components(output_root: Path) -> None:
    """Reject redirection through the output leaf or any existing parent.

    The rank-shard root is part of a content-addressed scientific identity.
    Resolving it would silently turn a symlink into a different publication
    target, while checking only the final component would still permit a
    symlinked parent to redirect locks, temporary trees, and the final rename.
    Missing parents are allowed for preparation, but every component that
    already exists must be a real directory.
    """

    if not output_root.is_absolute():
        raise ValueError(f"AS rank shard output root must be absolute: {output_root}")
    for parent in reversed(output_root.parents):
        try:
            parent_stat = parent.lstat()
        except FileNotFoundError:
            continue
        if stat.S_ISLNK(parent_stat.st_mode):
            raise ValueError(
                f"AS rank shard output parent must not be a symlink: {parent}"
            )
        if not stat.S_ISDIR(parent_stat.st_mode):
            raise ValueError(
                f"AS rank shard output parent is not a directory: {parent}"
            )
    try:
        output_stat = output_root.lstat()
    except FileNotFoundError:
        return
    if stat.S_ISLNK(output_stat.st_mode):
        raise ValueError(
            f"AS rank shard output root must not be a symlink: {output_root}"
        )


@contextmanager
def _output_lock(output_root: Path):
    _validate_output_path_components(output_root)
    output_root.parent.mkdir(parents=True, exist_ok=True)
    # mkdir(parents=True) may have created several components.  Re-open the
    # lexical path contract before even creating/opening the sibling lock.
    _validate_output_path_components(output_root)
    lock_path = output_root.parent / f".{output_root.name}.lock"
    with lock_path.open("a+b") as stream:
        fcntl.flock(stream.fileno(), fcntl.LOCK_EX)
        try:
            # Close the check-to-lock window.  Cooperative publishers now hold
            # the same lock, and a parent/leaf redirected before acquisition is
            # rejected before any temporary tree or published payload exists.
            _validate_output_path_components(output_root)
            yield
        finally:
            fcntl.flock(stream.fileno(), fcntl.LOCK_UN)


def _rename_exchange(first: Path, second: Path) -> None:
    libc = ctypes.CDLL(None, use_errno=True)
    renameat2 = getattr(libc, "renameat2", None)
    if renameat2 is None:
        raise RuntimeError(
            "Atomic replacement of an existing non-empty shard root requires Linux renameat2(RENAME_EXCHANGE)"
        )
    renameat2.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_uint]
    renameat2.restype = ctypes.c_int
    result = renameat2(
        _AT_FDCWD,
        os.fsencode(first),
        _AT_FDCWD,
        os.fsencode(second),
        _RENAME_EXCHANGE,
    )
    if result != 0:
        errno_value = ctypes.get_errno()
        raise OSError(errno_value, os.strerror(errno_value), f"{first} <-> {second}")


def _thaw_private_tree_for_removal(root: Path) -> None:
    """Make only a non-public tree removable without following its symlinks."""

    if root.is_symlink() or not root.is_dir():
        raise ValueError(f"Refusing to thaw a non-directory private shard tree: {root}")
    root.chmod(_PRIVATE_DIRECTORY_MODE)
    for current, child_dirs, _ in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        if current_path.is_symlink() or not current_path.is_dir():
            raise ValueError(f"Private shard tree changed while being removed: {current_path}")
        current_path.chmod(_PRIVATE_DIRECTORY_MODE)
        for name in child_dirs:
            child = current_path / name
            if not child.is_symlink():
                child.chmod(_PRIVATE_DIRECTORY_MODE)


def _remove_private_tree(root: Path) -> None:
    _thaw_private_tree_for_removal(root)
    shutil.rmtree(root)


def _atomic_publish(temp_root: Path, output_root: Path) -> None:
    # Revalidate immediately before the namespace-changing operation.  In
    # particular, never exchange a complete tree through a leaf or parent that
    # was replaced by a symlink after plan construction.
    _validate_output_path_components(output_root)
    if os.path.lexists(output_root):
        if output_root.is_symlink() or not output_root.is_dir() or not (output_root / _MARKER_NAME).is_file():
            raise ValueError(
                f"Refusing to replace non-generated AS rank shard root: {output_root}. "
                f"Remove it manually or choose a different --output-root."
            )
        # Both directories continue to exist throughout the exchange. Readers
        # see either the complete old tree or the complete new tree, never a
        # partially populated destination.
        _rename_exchange(temp_root, output_root)
        # After the exchange ``temp_root`` names the old tree and is no longer
        # public.  Only now may its sealed directories regain owner-write
        # permission so recursive removal can proceed.
        _remove_private_tree(temp_root)
    else:
        os.replace(temp_root, output_root)


def _fsync_tree(root: Path) -> None:
    directories = [root]
    for current, child_dirs, child_files in os.walk(root):
        current_path = Path(current)
        directories.extend(current_path / name for name in child_dirs)
        for name in child_files:
            path = current_path / name
            if path.is_symlink():
                continue
            with path.open("rb") as stream:
                os.fsync(stream.fileno())
    for directory in sorted(directories, key=lambda item: len(item.parts), reverse=True):
        descriptor = os.open(directory, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(descriptor)
        finally:
            os.close(descriptor)


def _rewrite_entry_paths(entry: dict[str, Any], *, source_base: Path, target_base: Path) -> dict[str, Any]:
    rewritten = dict(entry)
    for key in ("object_urdf_path", *_ENTRY_SINGLE_MESH_KEYS):
        raw = str(rewritten.get(key, "")).strip()
        if not raw:
            continue
        if raw.startswith(("package://", "http://", "https://", "file://")):
            continue
        rewritten[key] = _relpath(_resolve_path(raw, source_base), target_base)
    for key in ("object_urdf_paths", "object_urdfs", *_ENTRY_MULTI_MESH_KEYS):
        raw_values = _as_string_list(rewritten.get(key))
        if not raw_values:
            continue
        rewritten[key] = [
            raw
            if raw.startswith(("package://", "http://", "https://", "file://"))
            else _relpath(_resolve_path(raw, source_base), target_base)
            for raw in (str(item).strip() for item in raw_values)
            if raw
        ]
    return rewritten


def _pretty_json_bytes(value: Any) -> bytes:
    return json.dumps(value, indent=2, sort_keys=True).encode("utf-8")


def _path_has_mode(path: Path, expected_mode: int) -> bool:
    try:
        return stat.S_IMODE(path.lstat().st_mode) == expected_mode
    except OSError:
        return False


def _published_tree_has_sealed_modes(
    output_root: Path,
    *,
    expected_plan: RankShardPlan,
) -> bool:
    if not _path_has_mode(output_root, _SEALED_DIRECTORY_MODE):
        return False
    for name in (_MARKER_NAME, "manifest.json"):
        if not _path_has_mode(output_root / name, _SEALED_FILE_MODE):
            return False
    for rank_file in expected_plan.rank_files:
        rank_dir = output_root / f"rank_{rank_file.rank}"
        if not _path_has_mode(rank_dir, _SEALED_DIRECTORY_MODE):
            return False
        for name in ("_clip_object_urdf_map.json", "clip_ids.txt"):
            if not _path_has_mode(rank_dir / name, _SEALED_FILE_MODE):
                return False
    return True


def _chmod_nofollow(path: Path, mode: int, *, directory: bool) -> None:
    flags = os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW
    if directory:
        flags |= os.O_DIRECTORY
    descriptor = os.open(path, flags)
    try:
        file_stat = os.fstat(descriptor)
        if directory:
            valid_type = stat.S_ISDIR(file_stat.st_mode)
        else:
            valid_type = stat.S_ISREG(file_stat.st_mode)
        if not valid_type:
            expected = "directory" if directory else "regular file"
            raise ValueError(f"Expected {expected} while sealing AS rank shards: {path}")
        os.fchmod(descriptor, mode)
    finally:
        os.close(descriptor)


def _seal_generated_tree(
    output_root: Path,
    *,
    expected_plan: RankShardPlan,
) -> None:
    """Apply the v3 mode-only immutable publication contract."""

    for name in (_MARKER_NAME, "manifest.json"):
        _chmod_nofollow(output_root / name, _SEALED_FILE_MODE, directory=False)
    for rank_file in expected_plan.rank_files:
        rank_dir = output_root / f"rank_{rank_file.rank}"
        for name in ("_clip_object_urdf_map.json", "clip_ids.txt"):
            _chmod_nofollow(rank_dir / name, _SEALED_FILE_MODE, directory=False)
        _chmod_nofollow(rank_dir, _SEALED_DIRECTORY_MODE, directory=True)
    # Seal the root last so every child remains reachable throughout migration.
    _chmod_nofollow(output_root, _SEALED_DIRECTORY_MODE, directory=True)


def _build_rank_shard_file_plan(
    *,
    rank: int,
    published_rank_dir: Path,
    rank_units: list[AssignmentUnit],
    specs_by_clip: dict[str, ClipSpec],
    metadata: dict[str, Any],
    object_map: Path,
    world_size: int,
    strategy: str,
    global_clip_count: int,
    clip_cover_counts: dict[str, int],
    npz_records_by_clip: dict[str, dict[str, Any]],
) -> RankShardFilePlan:
    clip_ids = tuple(
        sorted(
            {
                clip_id
                for unit in rank_units
                for clip_id in unit.clip_ids
            }
        )
    )
    if not clip_ids:
        raise ValueError(f"Deterministic rank-shard plan produced an empty rank {rank}")

    npz_sources = tuple(specs_by_clip[clip_id].npz_path.resolve(strict=True) for clip_id in clip_ids)
    npz_link_targets = tuple(_relpath(path, published_rank_dir) for path in npz_sources)
    clips_payload = {
        clip_id: _rewrite_entry_paths(
            specs_by_clip[clip_id].entry,
            source_base=object_map.parent,
            target_base=published_rank_dir,
        )
        for clip_id in clip_ids
    }
    payload = dict(metadata)
    payload["clips"] = clips_payload
    transition_source = canonical_motion_transition_source(
        payload.get(MOTION_TRANSITION_SOURCE_KEY),
        active_clip_count=global_clip_count,
        role=f"rank {rank} {MOTION_TRANSITION_SOURCE_KEY}",
    )
    payload[MOTION_TRANSITION_SOURCE_KEY] = transition_source
    payload["rank_local_shard"] = {
        "rank": rank,
        "world_size": world_size,
        "strategy": strategy,
        "source_object_map": _relpath(object_map, published_rank_dir),
        "source_motion_dir": _relpath(
            specs_by_clip[clip_ids[0]].npz_path.parent,
            published_rank_dir,
        ),
        "global_clip_count": global_clip_count,
        "clip_cover_counts": {
            clip_id: int(clip_cover_counts[clip_id]) for clip_id in clip_ids
        },
        # This is transition lineage only.  It must never replace
        # ``global_clip_count``, which defines the active DDP objective.
        MOTION_TRANSITION_SOURCE_KEY: transition_source,
    }
    inverse_cover_mass = sum(
        1.0 / float(clip_cover_counts[clip_id]) for clip_id in clip_ids
    )
    payload["rank_local_shard"]["inverse_cover_mass"] = inverse_cover_mass
    payload["rank_local_shard"]["distributed_loss_weight"] = (
        float(world_size) * inverse_cover_mass / float(global_clip_count)
    )
    object_map_bytes = _pretty_json_bytes(payload)
    clip_ids_bytes = ("\n".join(clip_ids) + "\n").encode("utf-8")
    unique_urdfs = {
        str(path)
        for clip_id in clip_ids
        for path in specs_by_clip[clip_id].urdf_paths
    }
    npz_files = [dict(npz_records_by_clip[clip_id]) for clip_id in clip_ids]
    shard_record = {
        "rank": rank,
        "dir": str(published_rank_dir),
        "clip_count": len(clip_ids),
        "clip_ids": list(clip_ids),
        "unique_urdf_count": len(unique_urdfs),
        "weight": sum(unit.weight for unit in rank_units),
        "object_map_sha256": hashlib.sha256(object_map_bytes).hexdigest(),
        "npz_files": npz_files,
        "npz_content_sha256": _sha256_json(npz_files),
    }
    return RankShardFilePlan(
        rank=rank,
        rank_units=tuple(rank_units),
        clip_ids=clip_ids,
        object_map_bytes=object_map_bytes,
        clip_ids_bytes=clip_ids_bytes,
        npz_sources=npz_sources,
        npz_link_targets=npz_link_targets,
        shard_record=shard_record,
    )


def _build_rank_shard_plan(
    *,
    motion_dir: Path,
    object_map: Path,
    output_root: Path,
    world_size: int,
    environments_per_rank: int | None,
    source_digest: str,
    metadata: dict[str, Any],
    specs: list[ClipSpec],
) -> RankShardPlan:
    """Build the only accepted v3 rank tree directly from source inputs."""

    strategy, units = _assignment_units(specs, world_size)
    assignments, duplicated = _assign_units(
        units,
        world_size,
        environments_per_rank=environments_per_rank,
    )
    clip_cover_counts = {spec.clip_id: 0 for spec in specs}
    for rank_units in assignments:
        for clip_id in {
            clip_id
            for unit in rank_units
            for clip_id in unit.clip_ids
        }:
            clip_cover_counts[clip_id] += 1

    specs_by_clip = {spec.clip_id: spec for spec in specs}
    # Hash each source motion once.  A single-motion wsN view intentionally
    # repeats this record in N shard manifests without re-reading the same NPZ
    # N times.
    npz_records_by_clip = {
        spec.clip_id: _file_record(spec.npz_path) for spec in specs
    }
    rank_files = tuple(
        _build_rank_shard_file_plan(
            rank=rank,
            published_rank_dir=output_root / f"rank_{rank}",
            rank_units=rank_units,
            specs_by_clip=specs_by_clip,
            metadata=metadata,
            object_map=object_map,
            world_size=world_size,
            strategy=strategy,
            global_clip_count=len(specs),
            clip_cover_counts=clip_cover_counts,
            npz_records_by_clip=npz_records_by_clip,
        )
        for rank, rank_units in enumerate(assignments)
    )
    unique_urdfs = {str(path) for spec in specs for path in spec.urdf_paths}
    manifest = {
        "version": _MANIFEST_VERSION,
        "source_digest": source_digest,
        "motion_dir": str(motion_dir),
        "object_map": str(object_map),
        "output_root": str(output_root),
        "world_size": world_size,
        "strategy": strategy,
        "clip_count": len(specs),
        MOTION_TRANSITION_SOURCE_KEY: canonical_motion_transition_source(
            metadata.get(MOTION_TRANSITION_SOURCE_KEY),
            active_clip_count=len(specs),
            role=f"rank-shard manifest {MOTION_TRANSITION_SOURCE_KEY}",
        ),
        "unique_urdf_count": len(unique_urdfs),
        "exact_clip_partition": all(count == 1 for count in clip_cover_counts.values()),
        "duplicated_to_fill_empty_ranks": duplicated,
        "clip_cover_counts": clip_cover_counts,
        "shards": [rank_file.shard_record for rank_file in rank_files],
    }
    if environments_per_rank is not None:
        manifest["environments_per_rank"] = environments_per_rank
        manifest["rank_clip_counts_divide_environments_per_rank"] = all(
            environments_per_rank % int(rank_file.shard_record["clip_count"]) == 0
            for rank_file in rank_files
        )
    return RankShardPlan(manifest=manifest, rank_files=rank_files)


def _published_output_is_current(
    output_root: Path,
    *,
    expected_plan: RankShardPlan,
    require_sealed_modes: bool = True,
) -> tuple[bool, dict[str, Any] | None]:
    """Validate a published root against source-derived bytes, never itself."""

    try:
        if output_root.is_symlink() or not output_root.is_dir():
            return False, None
        expected_root_names = {
            _MARKER_NAME,
            "manifest.json",
            *(f"rank_{rank_file.rank}" for rank_file in expected_plan.rank_files),
        }
        if {path.name for path in output_root.iterdir()} != expected_root_names:
            return False, None

        marker_path = output_root / _MARKER_NAME
        manifest_path = output_root / "manifest.json"
        if (
            marker_path.is_symlink()
            or not marker_path.is_file()
            or marker_path.read_bytes() != _MARKER_BYTES
            or manifest_path.is_symlink()
            or not manifest_path.is_file()
        ):
            return False, None
        expected_manifest_bytes = _pretty_json_bytes(expected_plan.manifest)
        actual_manifest_bytes = manifest_path.read_bytes()
        if actual_manifest_bytes != expected_manifest_bytes:
            try:
                parsed = json.loads(actual_manifest_bytes.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError):
                parsed = None
            return False, parsed if isinstance(parsed, dict) else None
        manifest = json.loads(actual_manifest_bytes.decode("utf-8"))
        if manifest != expected_plan.manifest:
            return False, manifest if isinstance(manifest, dict) else None

        for rank_file in expected_plan.rank_files:
            rank_dir = output_root / f"rank_{rank_file.rank}"
            if rank_dir.is_symlink() or not rank_dir.is_dir():
                return False, manifest
            expected_rank_names = {
                "_clip_object_urdf_map.json",
                "clip_ids.txt",
                *(f"{clip_id}.npz" for clip_id in rank_file.clip_ids),
            }
            if {path.name for path in rank_dir.iterdir()} != expected_rank_names:
                return False, manifest

            local_map = rank_dir / "_clip_object_urdf_map.json"
            clip_list = rank_dir / "clip_ids.txt"
            if (
                local_map.is_symlink()
                or not local_map.is_file()
                or local_map.read_bytes() != rank_file.object_map_bytes
                or clip_list.is_symlink()
                or not clip_list.is_file()
                or clip_list.read_bytes() != rank_file.clip_ids_bytes
            ):
                return False, manifest

            actual_npz_records: list[dict[str, Any]] = []
            for index, clip_id in enumerate(rank_file.clip_ids):
                link = rank_dir / f"{clip_id}.npz"
                if not link.is_symlink():
                    return False, manifest
                if os.readlink(link) != rank_file.npz_link_targets[index]:
                    return False, manifest
                if link.resolve(strict=True) != rank_file.npz_sources[index]:
                    return False, manifest
                actual_npz_records.append(_file_record(link))
            if actual_npz_records != rank_file.shard_record["npz_files"]:
                return False, manifest
        if require_sealed_modes and not _published_tree_has_sealed_modes(
            output_root,
            expected_plan=expected_plan,
        ):
            return False, manifest
        return True, manifest
    except (KeyError, OSError, TypeError, ValueError, json.JSONDecodeError):
        return False, None


def _write_rank_shard(
    *,
    rank: int,
    rank_dir: Path,
    published_rank_dir: Path,
    rank_units: list[AssignmentUnit],
    specs_by_clip: dict[str, ClipSpec],
    metadata: dict[str, Any],
    object_map: Path,
    world_size: int,
    strategy: str,
    global_clip_count: int,
    clip_cover_counts: dict[str, int],
    rank_file_plan: RankShardFilePlan | None = None,
) -> dict[str, Any]:
    if rank_file_plan is None:
        npz_records_by_clip = {
            clip_id: _file_record(spec.npz_path)
            for clip_id, spec in specs_by_clip.items()
        }
        rank_file_plan = _build_rank_shard_file_plan(
            rank=rank,
            published_rank_dir=published_rank_dir,
            rank_units=rank_units,
            specs_by_clip=specs_by_clip,
            metadata=metadata,
            object_map=object_map,
            world_size=world_size,
            strategy=strategy,
            global_clip_count=global_clip_count,
            clip_cover_counts=clip_cover_counts,
            npz_records_by_clip=npz_records_by_clip,
        )
    rank_dir.mkdir(parents=True)
    for index, clip_id in enumerate(rank_file_plan.clip_ids):
        destination = rank_dir / f"{clip_id}.npz"
        destination.symlink_to(rank_file_plan.npz_link_targets[index])
        if destination.resolve(strict=True) != rank_file_plan.npz_sources[index]:
            raise RuntimeError(
                f"Rank {rank} NPZ link resolved outside its deterministic source plan: "
                f"{destination}"
            )
    (rank_dir / "_clip_object_urdf_map.json").write_bytes(
        rank_file_plan.object_map_bytes
    )
    (rank_dir / "clip_ids.txt").write_bytes(rank_file_plan.clip_ids_bytes)
    return rank_file_plan.shard_record


def validate_published_rank_shards(
    *,
    motion_dir: Path,
    object_map: Path,
    output_root: Path,
    world_size: int,
    environments_per_rank: int | None = None,
    expected_source_digest: str | None = None,
) -> dict[str, Any]:
    """Read-only validation of one published tree against its source plan.

    This deliberately does not acquire the publication lock or create any
    directory.  Launch preflights can therefore prove an existing rank-local
    view without gaining an implicit repair/materialization capability.
    """

    if world_size < 1:
        raise ValueError(f"world_size must be >= 1, got {world_size}")
    if environments_per_rank is not None and environments_per_rank < 1:
        raise ValueError(
            f"environments_per_rank must be >= 1, got {environments_per_rank}"
        )
    motion_dir = motion_dir.expanduser().resolve(strict=True)
    object_map = object_map.expanduser().resolve(strict=True)
    output_root = _lexical_absolute_path(output_root)
    _validate_output_path_components(output_root)
    if not output_root.exists():
        raise ValueError(
            f"Published AS rank shard root does not exist: {output_root}"
        )
    if not output_root.is_dir():
        raise ValueError(f"Published AS rank shard root is not a directory: {output_root}")

    source_guard = _SourceScanGuard()
    metadata, specs = _active_clip_specs(
        motion_dir=motion_dir,
        object_map=object_map,
        source_guard=source_guard,
    )
    source_digest = _rank_shard_source_digest_from_specs(
        motion_dir=motion_dir,
        object_map=object_map,
        specs=specs,
        world_size=world_size,
        environments_per_rank=environments_per_rank,
        source_guard=source_guard,
    )
    if expected_source_digest is not None and source_digest != expected_source_digest:
        raise RuntimeError(
            "Rank-shard source differs from the expected published identity: "
            f"expected={expected_source_digest}, actual={source_digest}"
        )
    expected_plan = _build_rank_shard_plan(
        motion_dir=motion_dir,
        object_map=object_map,
        output_root=output_root,
        world_size=world_size,
        environments_per_rank=environments_per_rank,
        source_digest=source_digest,
        metadata=metadata,
        specs=specs,
    )
    current, manifest = _published_output_is_current(
        output_root,
        expected_plan=expected_plan,
    )
    source_guard.verify()
    if not current or manifest != expected_plan.manifest:
        raise ValueError(
            "Published AS rank shard tree differs from its source-derived deterministic plan: "
            f"{output_root}"
        )
    return manifest


def prepare_rank_shards(
    *,
    motion_dir: Path,
    object_map: Path,
    output_root: Path,
    world_size: int,
    environments_per_rank: int | None = None,
    expected_source_digest: str | None = None,
) -> dict[str, Any]:
    if world_size < 1:
        raise ValueError(f"world_size must be >= 1, got {world_size}")
    if environments_per_rank is not None and environments_per_rank < 1:
        raise ValueError(
            f"environments_per_rank must be >= 1, got {environments_per_rank}"
        )
    motion_dir = motion_dir.expanduser().resolve(strict=True)
    object_map = object_map.expanduser().resolve(strict=True)
    output_root = _lexical_absolute_path(output_root)
    # This first check occurs before _output_lock is allowed to mkdir a missing
    # parent or open its lock file.  The context manager repeats it after mkdir
    # and after lock acquisition to close both state-transition windows.
    _validate_output_path_components(output_root)
    if output_root.exists():
        try:
            return validate_published_rank_shards(
                motion_dir=motion_dir,
                object_map=object_map,
                output_root=output_root,
                world_size=world_size,
                environments_per_rank=environments_per_rank,
                expected_source_digest=expected_source_digest,
            )
        except ValueError:
            # Preserve the existing repair/reject behavior for a non-current
            # publication.  A current sealed tree has already returned without
            # creating a lock beside its read-only namespace.
            pass
    with _output_lock(output_root):
        source_guard = _SourceScanGuard()
        metadata, specs = _active_clip_specs(
            motion_dir=motion_dir,
            object_map=object_map,
            source_guard=source_guard,
        )
        source_digest = _rank_shard_source_digest_from_specs(
            motion_dir=motion_dir,
            object_map=object_map,
            specs=specs,
            world_size=world_size,
            environments_per_rank=environments_per_rank,
            source_guard=source_guard,
        )
        if expected_source_digest is not None and source_digest != expected_source_digest:
            raise RuntimeError(
                "Rank-shard source changed after its output path was selected: "
                f"expected={expected_source_digest}, actual={source_digest}"
            )
        expected_plan = _build_rank_shard_plan(
            motion_dir=motion_dir,
            object_map=object_map,
            output_root=output_root,
            world_size=world_size,
            environments_per_rank=environments_per_rank,
            source_digest=source_digest,
            metadata=metadata,
            specs=specs,
        )
        current, current_manifest = _published_output_is_current(
            output_root,
            expected_plan=expected_plan,
            require_sealed_modes=False,
        )
        if current:
            assert current_manifest is not None
            # The plan and published tree were inspected after the source
            # digest pass.  Re-open every retained lexical dependency before
            # returning so the current fast path cannot accept a source that
            # changed during that comparison.
            source_guard.verify()
            if not _published_tree_has_sealed_modes(
                output_root,
                expected_plan=expected_plan,
            ):
                _seal_generated_tree(output_root, expected_plan=expected_plan)
                _fsync_tree(output_root)
            sealed_current, sealed_manifest = _published_output_is_current(
                output_root,
                expected_plan=expected_plan,
            )
            source_guard.verify()
            if not sealed_current or sealed_manifest != expected_plan.manifest:
                raise RuntimeError(
                    "Sealed AS rank shard tree differs from its source-derived deterministic plan: "
                    f"{output_root}"
                )
            return sealed_manifest
        if expected_source_digest is not None and os.path.lexists(output_root):
            raise ValueError(
                "Refusing to replace an invalid immutable/content-addressed AS rank shard root: "
                f"{output_root}. A launch that supplies --expected-source-digest must never "
                "repair or redirect an existing source identity in place."
            )
        if os.path.lexists(output_root) and (
            output_root.is_symlink()
            or not output_root.is_dir()
            or not (output_root / _MARKER_NAME).is_file()
        ):
            raise ValueError(
                f"Refusing to replace non-generated AS rank shard root: {output_root}. "
                f"Remove it manually or choose a different --output-root."
            )

        temp_root = Path(
            tempfile.mkdtemp(prefix=f".{output_root.name}.tmp-", dir=output_root.parent)
        )
        try:
            (temp_root / _MARKER_NAME).write_bytes(_MARKER_BYTES)
            specs_by_clip = {spec.clip_id: spec for spec in specs}
            shards = []
            for rank_file_plan in expected_plan.rank_files:
                rank = rank_file_plan.rank
                rank_dir = temp_root / f"rank_{rank}"
                shard = _write_rank_shard(
                    rank=rank,
                    rank_dir=rank_dir,
                    published_rank_dir=output_root / f"rank_{rank}",
                    rank_units=list(rank_file_plan.rank_units),
                    specs_by_clip=specs_by_clip,
                    metadata=metadata,
                    object_map=object_map,
                    world_size=world_size,
                    strategy=str(expected_plan.manifest["strategy"]),
                    global_clip_count=len(specs),
                    clip_cover_counts=dict(expected_plan.manifest["clip_cover_counts"]),
                    rank_file_plan=rank_file_plan,
                )
                if shard != rank_file_plan.shard_record:
                    raise RuntimeError(
                        f"Rank {rank} writer returned bytes outside its deterministic plan"
                    )
                shards.append(shard)
            if shards != expected_plan.manifest["shards"]:
                raise RuntimeError("Rank writers diverged from the deterministic manifest plan")
            manifest = expected_plan.manifest
            final_source_guard = _SourceScanGuard()
            _, final_specs = _active_clip_specs(
                motion_dir=motion_dir,
                object_map=object_map,
                source_guard=final_source_guard,
            )
            final_source_digest = _rank_shard_source_digest_from_specs(
                motion_dir=motion_dir,
                object_map=object_map,
                specs=final_specs,
                world_size=world_size,
                environments_per_rank=environments_per_rank,
                source_guard=final_source_guard,
            )
            if final_source_digest != source_digest:
                raise RuntimeError(
                    "Rank-shard source changed while its replacement was being built; "
                    f"before={source_digest}, after={final_source_digest}"
                )
            (temp_root / "manifest.json").write_bytes(_pretty_json_bytes(manifest))
            _seal_generated_tree(temp_root, expected_plan=expected_plan)
            temp_current, temp_manifest = _published_output_is_current(
                temp_root,
                expected_plan=expected_plan,
            )
            if not temp_current or temp_manifest != manifest:
                raise RuntimeError(
                    "Sealed temporary AS rank shard tree differs from its deterministic plan: "
                    f"{temp_root}"
                )
            _fsync_tree(temp_root)
            _atomic_publish(temp_root, output_root)
            parent_fd = os.open(output_root.parent, os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(parent_fd)
            finally:
                os.close(parent_fd)
            published_current, published_manifest = _published_output_is_current(
                output_root,
                expected_plan=expected_plan,
            )
            if not published_current or published_manifest != manifest:
                raise RuntimeError(
                    "Published AS rank shard tree differs from its source-derived deterministic plan: "
                    f"{output_root}"
                )
            final_source_guard.verify()
        finally:
            if temp_root.exists():
                _remove_private_tree(temp_root)
        return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--motion-dir", required=True, type=Path)
    parser.add_argument("--object-map", required=True, type=Path)
    parser.add_argument("--output-root", type=Path)
    parser.add_argument("--world-size", required=True, type=int)
    parser.add_argument(
        "--environments-per-rank",
        type=int,
        help=(
            "Require every rank-local clip count to divide this environment count, "
            "so fixed env-to-clip assignment can represent uniform clip mass exactly."
        ),
    )
    parser.add_argument("--source-digest-only", action="store_true")
    parser.add_argument("--expected-source-digest")
    args = parser.parse_args()

    motion_dir = args.motion_dir.expanduser().resolve()
    object_map = args.object_map.expanduser().resolve()
    if args.source_digest_only:
        try:
            print(
                compute_rank_shard_source_digest(
                    motion_dir=motion_dir,
                    object_map=object_map,
                    world_size=args.world_size,
                    environments_per_rank=args.environments_per_rank,
                )
            )
        except Exception as exc:
            print(f"[ERROR] Failed to digest AS rank-local shard inputs: {exc}", file=sys.stderr)
            return 2
        return 0
    if args.output_root is None:
        parser.error("--output-root is required unless --source-digest-only is used")
    # Preserve the caller's normalized lexical publication path.  Resolving it
    # here would erase a final/parent symlink before the publisher can reject
    # that redirection.
    output_root = _lexical_absolute_path(args.output_root)

    try:
        manifest = prepare_rank_shards(
            motion_dir=motion_dir,
            object_map=object_map,
            output_root=output_root,
            world_size=args.world_size,
            environments_per_rank=args.environments_per_rank,
            expected_source_digest=args.expected_source_digest,
        )
    except Exception as exc:
        print(f"[ERROR] Failed to prepare AS rank-local shards: {exc}", file=sys.stderr)
        return 2

    print(f"[INFO] Prepared AS rank-local motion shards: {output_root}", file=sys.stderr)
    print(
        "[INFO]   "
        f"world_size={manifest['world_size']} strategy={manifest['strategy']} "
        f"clips={manifest['clip_count']} unique_urdfs={manifest['unique_urdf_count']} "
        f"exact_clip_partition={manifest['exact_clip_partition']}",
        file=sys.stderr,
    )
    if manifest["duplicated_to_fill_empty_ranks"]:
        print(
            "[WARN]   world_size exceeds available assignment units; some clips were duplicated to avoid empty ranks.",
            file=sys.stderr,
        )
    print(str(output_root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
